{% set name = "qed" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/aivazis/qed/archive/v{{ version }}.tar.gz
    sha256: 18cfa8461fd273f815e433cfe80eeb69174a1b8b62fc0b81dd0b403d74272d1a

build:
  number: 0
  skip: true  # [win or py2k or python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - hdf5
    - numpy
    - pybind11
    - pyre
    - python
    - zip
  run:
    - python
    - pyre

test:
  requires:
    - cmake
  commands:
    - ctest --output-on-failure
  imports:
    - qed

about:
  home: http://github.com/aivazis/qed
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A web based visualization tool for large raster data

  description: |
    A web based visualization tool for large raster data

  dev_url: https://github.com/aivazis/qed
  doc_url: http://guthub.com/aivazis/qed

extra:
  recipe-maintainers:
    - aivazis
