{% set name = "mm" %}
{% set version = "4.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/aivazis/mm/archive/v{{ version }}.tar.gz
    sha256: bd8c9309965b78b956c27347811f0e1601152dd35f57e75eeccb5481e0190af8

build:
  noarch: python
  number: 0

requirements:
  build:
  host:
    - zip
    - python # > 3.7.2
  run:
    - make # > 4.2.1
    - python # > 3.7.2
    - pyre

test:
  commands:
    - mm --help

about:
  home: http://github.com/aivazis/mm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A framework for building projects based on GNU make

  description: |
    A framework for building projects based on GNU make

  dev_url: https://github.com/aivazis/mm
  doc_url: http://guthub.com/aivazis/mm

extra:
  recipe-maintainers:
    - aivazis
